name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Image Tag
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF_NAME} | tr '/' '-')" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Clean
        run: |
          cd ..
          cd  appmenu
          mvn clean

      - name: Maven Compile
        run: |
          cd ..
          cd appmenu
          mvn compile



      - name: Maven Build (Skip Tests)
        run: |
          cd ..
          cd  appmenu
          mvn install -DskipTests=true

      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projet-fed-back:${{ env.IMAGE_TAG }} .


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/projet-fed-back:${{ env.IMAGE_TAG }}
      - name: Notify (Simple)
        if: always()
        run: |
          echo "Pipeline finished with status: ${{ job.status }}"